# Generated by Django 6.0.4 on 2026-04-13 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Providers",
            fields=[
                ("provider_id", models.AutoField(primary_key=True, serialize=False)),
                ("provider_name", models.CharField(max_length=100)),
                ("provider_address", models.CharField(max_length=100)),
                ("provider_city", models.CharField(max_length=100)),
                ("provider_state", models.CharField(max_length=100)),
                ("provider_phone", models.CharField(blank=True, max_length=20)),
                ("provider_email", models.EmailField(blank=True, max_length=254)),
                (
                    "provider_type",
                    models.CharField(
                        choices=[("public", "Public"), ("private", "Private")],
                        default="private",
                        max_length=20,
                    ),
                ),
                (
                    "latitude",
                    models.DecimalField(
                        blank=True, decimal_places=6, max_digits=9, null=True
                    ),
                ),
                (
                    "longitude",
                    models.DecimalField(
                        blank=True, decimal_places=6, max_digits=9, null=True
                    ),
                ),
                ("is_verified", models.BooleanField(default=False)),
                ("license_number", models.CharField(blank=True, max_length=100)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name_plural": "Providers",
            },
        ),
    ]
