# Generated by Django 6.0.4 on 2026-04-13 17:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("providers", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Facilities",
            fields=[
                ("facility_id", models.AutoField(primary_key=True, serialize=False)),
                ("facility_name", models.CharField(max_length=100)),
                ("facility_address", models.CharField(blank=True, max_length=200)),
                ("facility_city", models.CharField(max_length=100)),
                ("facility_state", models.CharField(max_length=100)),
                (
                    "facility_type",
                    models.CharField(
                        choices=[
                            ("public", "Public"),
                            ("private", "Private"),
                            ("pharmacy", "Pharmacy"),
                        ],
                        default="private",
                        max_length=20,
                    ),
                ),
                (
                    "latitude",
                    models.DecimalField(
                        blank=True, decimal_places=6, max_digits=9, null=True
                    ),
                ),
                (
                    "longitude",
                    models.DecimalField(
                        blank=True, decimal_places=6, max_digits=9, null=True
                    ),
                ),
                ("is_verified", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "provider",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="facilities",
                        to="providers.providers",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Facilities",
            },
        ),
    ]
