# Generated by Django 6.0.4 on 2026-04-13 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("facilities", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="facilities",
            name="procedures",
            field=models.TextField(
                default="General Consultation",
                help_text="Comma separated list of procedures, e.g., Surgery, Dental, X-Ray",
            ),
        ),
        migrations.AddField(
            model_name="facilities",
            name="rating",
            field=models.DecimalField(decimal_places=1, default=4.0, max_digits=3),
        ),
        migrations.AlterField(
            model_name="facilities",
            name="is_verified",
            field=models.BooleanField(default=True),
        ),
    ]
