# Generated by Django 6.0.3 on 2026-04-19 09:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facilities', '0003_facilityprocedure'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProcedureLibrary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True)),
                ('category', models.CharField(choices=[('diagnostics', 'Diagnostics & Lab Tests'), ('imaging', 'Imaging & Radiology'), ('consultation', 'Consultation'), ('surgery', 'Surgery & Procedures'), ('dental', 'Dental'), ('maternity', 'Maternity & Gynaecology'), ('pharmacy', 'Pharmacy & Drugs'), ('physiotherapy', 'Physiotherapy'), ('eye', 'Eye Care'), ('mental_health', 'Mental Health'), ('emergency', 'Emergency Care'), ('other', 'Other')], default='other', max_length=50)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'Procedure Library',
                'ordering': ['category', 'name'],
            },
        ),
        migrations.AlterModelOptions(
            name='facilityprocedure',
            options={'ordering': ['procedure_name']},
        ),
        migrations.AddField(
            model_name='facilities',
            name='verified_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='facilities',
            name='is_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='facilities',
            name='procedures',
            field=models.TextField(default='General Consultation', help_text='Comma separated list of procedures'),
        ),
        migrations.AlterField(
            model_name='facilityprocedure',
            name='procedure_name',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterUniqueTogether(
            name='facilityprocedure',
            unique_together={('facility', 'procedure_name')},
        ),
        migrations.AddField(
            model_name='facilityprocedure',
            name='procedure_library',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='facility_prices', to='facilities.procedurelibrary'),
        ),
    ]
