# Generated by Django 6.0.3 on 2026-04-21 10:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('facilities', '0005_remove_facilities_provider_and_more'),
        ('reports', '0002_alter_report_facility'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Facilities',
        ),
    ]
