# Generated by Django 6.0.3 on 2026-04-21 17:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facilities', '0006_delete_facilities'),
        ('providers', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='facility',
            name='claimed_by',
        ),
        migrations.AlterModelOptions(
            name='communitypricesubmission',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='facilityclaim',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='facilityprocedure',
            options={'ordering': ['procedure_name']},
        ),
        migrations.AlterModelOptions(
            name='pricehistory',
            options={'ordering': ['-changed_at']},
        ),
        migrations.RenameField(
            model_name='communitypricesubmission',
            old_name='submitted_at',
            new_name='created_at',
        ),
        migrations.RenameField(
            model_name='communitypricesubmission',
            old_name='is_merged',
            new_name='is_verified',
        ),
        migrations.AddField(
            model_name='communitypricesubmission',
            name='visited_on',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='facilityclaim',
            name='notes',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='facilityclaim',
            name='provider_user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='facility_claims', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='communitypricesubmission',
            name='submitted_by',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='community_submissions', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='facilityclaim',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='facilityprocedure',
            name='community_submission_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='facilityprocedure',
            name='price_source',
            field=models.CharField(choices=[('provider', 'Provider Official'), ('community', 'Community Reported'), ('admin', 'Admin')], default='provider', max_length=20),
        ),
        migrations.AlterField(
            model_name='facilityprocedure',
            name='procedure_library',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='facility_prices', to='facilities.procedurelibrary'),
        ),
        migrations.AlterField(
            model_name='pricehistory',
            name='changed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='price_changes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='Facilities',
            fields=[
                ('facility_id', models.AutoField(primary_key=True, serialize=False)),
                ('facility_name', models.CharField(max_length=200)),
                ('facility_address', models.CharField(blank=True, max_length=300)),
                ('facility_city', models.CharField(max_length=100)),
                ('facility_state', models.CharField(max_length=100)),
                ('facility_type', models.CharField(choices=[('public', 'Public'), ('private', 'Private'), ('pharmacy', 'Pharmacy')], default='private', max_length=20)),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('phone', models.CharField(blank=True, max_length=50)),
                ('opening_hours', models.JSONField(blank=True, null=True)),
                ('osm_id', models.CharField(blank=True, max_length=50, null=True, unique=True)),
                ('osm_synced_at', models.DateTimeField(blank=True, null=True)),
                ('data_source', models.CharField(choices=[('osm', 'OpenStreetMap'), ('admin', 'Admin'), ('provider', 'Provider')], default='provider', max_length=20)),
                ('is_claimed', models.BooleanField(default=False)),
                ('is_verified', models.BooleanField(default=False)),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
                ('procedures', models.TextField(blank=True, default='General Consultation')),
                ('rating', models.DecimalField(decimal_places=1, default=4.0, max_digits=3)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('claimed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='claimed_facilities', to=settings.AUTH_USER_MODEL)),
                ('provider', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='facilities', to='providers.providers')),
            ],
            options={
                'verbose_name_plural': 'Facilities',
            },
        ),
        migrations.AlterField(
            model_name='communitypricesubmission',
            name='facility',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='community_prices', to='facilities.facilities'),
        ),
        migrations.AlterField(
            model_name='facilityclaim',
            name='facility',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='claims', to='facilities.facilities'),
        ),
        migrations.AlterField(
            model_name='facilityprocedure',
            name='facility',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pricing', to='facilities.facilities'),
        ),
        migrations.AlterUniqueTogether(
            name='facilityclaim',
            unique_together={('facility', 'provider_user')},
        ),
    ]
