# Generated by Django 6.0.3 on 2026-04-21 17:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('facilities', '0007_remove_facility_claimed_by_and_more'),
        ('reports', '0003_alter_report_facility'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Facility',
        ),
        migrations.RemoveField(
            model_name='facilityclaim',
            name='provider',
        ),
    ]
