# Generated by Django 6.0.3 on 2026-04-21 17:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facilities', '0007_remove_facility_claimed_by_and_more'),
        ('reports', '0002_alter_report_facility'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='facility',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports', to='facilities.facilities'),
        ),
    ]
